---
title: "AGU24 Supplementary Materials"
output: html_document
author: "Annie Edwards"
date: "Presented: Thursday, 12 December 2024; 08:30 - 12:20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r install libraries, include=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library("here")
library(ggnewscale)
library(shades)
```

```{r import dataframes, include=FALSE}
sheet <- "EA_summary.xlsx"

stream_distance <- read_excel(here("EA-IRMS","summaries", sheet), 1)
d13C <- read_excel(here("EA-IRMS","summaries", sheet), 2)
d15N <- read_excel(here("EA-IRMS","summaries", sheet), 3)
OC <- read_excel(here("EA-IRMS","summaries", sheet), 4)
CN <- read_excel(here("EA-IRMS","summaries", sheet), 5)

```

```{r lengthen, include=FALSE}
d13C_long <- pivot_longer(d13C, cols = starts_with("core"))
d15N_long <- pivot_longer(d15N, cols = starts_with("core"))
OC_long <- pivot_longer(OC, cols = starts_with("core"))
CN_long <- pivot_longer(CN, cols = starts_with("core"))

CN_woCore11 <- subset(CN, select = -core11C)
CN_woCore11_long <- pivot_longer(CN_woCore11, cols = starts_with("Core"))

d13C_long <- d13C_long %>% 
  inner_join(stream_distance, by = "name")
d15N_long <- d15N_long %>% 
  inner_join(stream_distance, by = "name")
OC_long <- OC_long %>% 
  inner_join(stream_distance, by = "name")
CN_long <- CN_long %>% 
  inner_join(stream_distance, by = "name")
```

```{r contour plot, echo=FALSE, warning=FALSE, messages=FALSE}
contourtheme <- theme(panel.background=element_blank(),
                      panel.grid=element_blank(), 
                      axis.line=element_line(size = 1, 
                                             colour = "black"),
                      axis.ticks=element_line(size = 1, 
                                              colour = "black"),
                      axis.text=element_text(color = "black", 
                                             size = 10),
                      axis.title=element_text(color="black"),
                      rect=element_rect(fill = "transparent"),
                      strip.background=element_blank(),
                      strip.text=element_blank(),
                      plot.background=element_blank(),
                      axis.line.x.bottom=element_blank(),
                      axis.text.x.bottom=element_text(color = "black", 
                                                      size = 10, angle = 45, 
                                                      hjust = 1),
                      axis.ticks.x.bottom=element_line(color = "black"),
                      axis.ticks.x.bottom.length=unit(5,"picas"),
                      legend.key.size = unit(1, 'cm')
                      )
suppressMessages(
  d13C_long %>%
    ggplot(., aes(x = stream_distance-10, y = depth_midpt, z = value, color = value)) +
      scale_fill_viridis_c(option="turbo", name = expression(delta^13~C)) +
      geom_point(col = "transparent", aes(fill = value)) +
      new_scale("fill") +
      scale_fill_viridis_d(option="turbo", guide = "none") +
      geom_contour_filled() +
      new_scale("fill") + 
      lightness(scale_fill_viridis_c(option="turbo", guide = "none"), delta(-20)) +
      geom_point(pch =21, col = "transparent", aes(fill = value)) +
      contourtheme +
      ylim(118,0) + xlim(0, 460) +
      xlab("Distance from River Channel (m)") + ylab("Depth (cm)") +
      scale_x_continuous(position="top",
                         sec.axis = sec_axis(~. +10, 
                                             breaks=c(10, 93, 187, 312, 466), 
                                             labels=c("Core 01",
                                                      "Core 05", 
                                                      "Core 07",
                                                      "Core 09",
                                                      "Core 11")
                                             )
                         )
)
```
